/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2016-01-26 05:58:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/_editor.jsp", Long.valueOf(1453787615348L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/francisBlog/css/fsblog.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/francisBlog/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/francisBlog/css/font-awesome.min.css\">\r\n");
      out.write("    <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/francisBlog/js/fsblog.js\"></script>\r\n");
      out.write("    <script src=\"/francisBlog/js/bootstrap-wysiwyg.js\"></script>\r\n");
      out.write("    <script src=\"/francisBlog/js/jquery.hotkeys.js\"></script>\r\n");
      out.write("    <script src=\"/francisBlog/js/prettify.js\"></script>\r\n");
      out.write("    <!--    <link rel=\"stylesheet\" href=\"/francisBlog/css/bootstrap.css\">-->\r\n");
      out.write("    <title>首页</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"fs-menu\">\r\n");
      out.write("        <nav class=\"navbar-fixed-top navbar-inverse\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <ul class=\"nav nav-pills\">\r\n");
      out.write("              <li role=\"presentation\" class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("              <li role=\"presentation\"><a href=\"#\">Profile</a></li>\r\n");
      out.write("              <li role=\"presentation\"><a href=\"#\">Messages</a></li>\r\n");
      out.write("              <li  class=\"fs-float-right\" role=\"presentation\"><a class=\"fs-float-right\" id=\"login\" href=\"#\">Login</a></li>\r\n");
      out.write("              <li  class=\"fs-float-right\" role=\"presentation\"><a class=\"fs-float-right\" href=\"#\">Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"fs-top\">\r\n");
      out.write("        <div class=\"fs-top-user fs-float-left\">\r\n");
      out.write("          莫显乎微\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"fs-row-fluid\">\r\n");
      out.write("          <div class=\"fs-span3\">\r\n");
      out.write("            日历。。。\r\n");
      out.write("            <img src=\"/francisBlog/img/calendar.jpg\">\r\n");
      out.write("            <h3>导航1</h3>\r\n");
      out.write("            <h3>导航2</h3>\r\n");
      out.write("            <h3>导航3</h3>\r\n");
      out.write("            <h3>导航4</h3>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"fs-span9\">\r\n");
      out.write("            <ul class=\"nav nav-tabs\">\r\n");
      out.write("              <li role=\"presentation\" class=\"active\"><a href=\"#\">已发表文章</a></li>\r\n");
      out.write("              <li role=\"presentation\"><a href=\"#\">写文章</a></li>\r\n");
      out.write("              <li role=\"presentation\"><a href=\"#\">新评论<span class=\"badge\">42</span></a></li>\r\n");
      out.write("              <li role=\"presentation\"><a href=\"#\">提示</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"testcontent\">\r\n");
      out.write("              ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/login.jsp", out, true);
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div>\r\n");
      out.write("              ");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"alerts\"></div>\r\n");
      out.write("      <div class=\"btn-toolbar\" data-role=\"editor-toolbar\" data-target=\"#editor\">\r\n");
      out.write("        <div class=\"btn-group\">\r\n");
      out.write("          <a class=\"btn dropdown-toggle\" data-toggle=\"dropdown\" title=\"Font\"><i class=\"icon-font\"></i><b class=\"caret\"></b></a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        <div class=\"btn-group\">\r\n");
      out.write("          <a class=\"btn dropdown-toggle\" data-toggle=\"dropdown\" title=\"Font Size\"><i class=\"icon-text-height\"></i>&nbsp;<b class=\"caret\"></b></a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a data-edit=\"fontSize 5\"><font size=\"5\">Huge</font></a></li>\r\n");
      out.write("            <li><a data-edit=\"fontSize 3\"><font size=\"3\">Normal</font></a></li>\r\n");
      out.write("            <li><a data-edit=\"fontSize 1\"><font size=\"1\">Small</font></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"btn-group\">\r\n");
      out.write("          <a class=\"btn\" data-edit=\"bold\" title=\"Bold (Ctrl/Cmd+B)\"><i class=\"icon-bold\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"italic\" title=\"Italic (Ctrl/Cmd+I)\"><i class=\"icon-italic\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"strikethrough\" title=\"Strikethrough\"><i class=\"icon-strikethrough\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"underline\" title=\"Underline (Ctrl/Cmd+U)\"><i class=\"icon-underline\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"btn-group\">\r\n");
      out.write("          <a class=\"btn\" data-edit=\"insertunorderedlist\" title=\"Bullet list\"><i class=\"icon-list-ul\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"insertorderedlist\" title=\"Number list\"><i class=\"icon-list-ol\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"outdent\" title=\"Reduce indent (Shift+Tab)\"><i class=\"icon-indent-left\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"indent\" title=\"Indent (Tab)\"><i class=\"icon-indent-right\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"btn-group\">\r\n");
      out.write("          <a class=\"btn\" data-edit=\"justifyleft\" title=\"Align Left (Ctrl/Cmd+L)\"><i class=\"icon-align-left\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"justifycenter\" title=\"Center (Ctrl/Cmd+E)\"><i class=\"icon-align-center\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"justifyright\" title=\"Align Right (Ctrl/Cmd+R)\"><i class=\"icon-align-right\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"justifyfull\" title=\"Justify (Ctrl/Cmd+J)\"><i class=\"icon-align-justify\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"btn-group\">\r\n");
      out.write("        <a class=\"btn dropdown-toggle\" data-toggle=\"dropdown\" title=\"Hyperlink\"><i class=\"icon-link\"></i></a>\r\n");
      out.write("          <div class=\"dropdown-menu input-append\">\r\n");
      out.write("            <input class=\"span2\" placeholder=\"URL\" type=\"text\" data-edit=\"createLink\"/>\r\n");
      out.write("            <button class=\"btn\" type=\"button\">Add</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"unlink\" title=\"Remove Hyperlink\"><i class=\"icon-cut\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"btn-group\">\r\n");
      out.write("          <a class=\"btn\" title=\"Insert picture (or just drag & drop)\" id=\"pictureBtn\"><i class=\"icon-picture\"></i></a>\r\n");
      out.write("          <input type=\"file\" data-role=\"magic-overlay\" data-target=\"#pictureBtn\" data-edit=\"insertImage\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"btn-group\">\r\n");
      out.write("          <a class=\"btn\" data-edit=\"undo\" title=\"Undo (Ctrl/Cmd+Z)\"><i class=\"icon-undo\"></i></a>\r\n");
      out.write("          <a class=\"btn\" data-edit=\"redo\" title=\"Redo (Ctrl/Cmd+Y)\"><i class=\"icon-repeat\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"text\" data-edit=\"inserttext\" id=\"voiceBtn\" x-webkit-speech=\"\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"editor\">\r\n");
      out.write("        Go ahead&hellip;\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <nav>\r\n");
      out.write("              <ul class=\"pager\">\r\n");
      out.write("                <li><a href=\"#\">Previous</a></li>\r\n");
      out.write("                <li><a href=\"#\">Next</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
